name: flutter_task_calendar
description: Um app Flutter com login, calendário e lista de tarefas com Hive.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localização e internacionalização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Interface do calendário
  table_calendar: ^3.1.1

  # Criptografia para senhas
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramentas de geração e build
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
